const ACTION_CHANGE_MAIN_FILTER_TEXT = 'ACTION_CHANGE_MAIN_FILTER_TEXT';
const ACTION_CHANGE_ROWS_DATA = 'ACTION_CHANGE_ROWS_DATA';
const ACTION_CHANGE_NAME_FILTER_TEXT = 'ACTION_CHANGE_NAME_FILTER_TEXT';
const ACTION_CHANGE_LOCATION_FILTER_TEXT = 'ACTION_CHANGE_LOCATION_FILTER_TEXT';
const ACTION_CHANGE_CHECKBOX_YES = 'ACTION_CHANGE_CHECKBOX_YES';
const ACTION_CHANGE_CHECKBOX_NO = 'ACTION_CHANGE_CHECKBOX_NO';
const ACTION_CHANGE_CHECKBOX_VIRTUALIZATION = 'ACTION_CHANGE_CHECKBOX_VIRTUALIZATION';
const ACTION_CHANGE_SELECTED_LANGUAGES = 'ACTION_CHANGE_SELECTED_LANGUAGES';
const ACTION_CHANGE_SELECTED_RATING = 'ACTION_CHANGE_SELECTED_RATING';
const ACTION_CHANGE_SORT_LOCATION = 'ACTION_CHANGE_SORT_LOCATION';
const ACTION_CHANGE_SORT_NAME = 'ACTION_CHANGE_SORT_NAME';

export {
  ACTION_CHANGE_MAIN_FILTER_TEXT,
  ACTION_CHANGE_NAME_FILTER_TEXT,
  ACTION_CHANGE_LOCATION_FILTER_TEXT,
  ACTION_CHANGE_ROWS_DATA,
  ACTION_CHANGE_CHECKBOX_YES,
  ACTION_CHANGE_CHECKBOX_NO,
  ACTION_CHANGE_SELECTED_LANGUAGES,
  ACTION_CHANGE_SELECTED_RATING,
  ACTION_CHANGE_CHECKBOX_VIRTUALIZATION,
  ACTION_CHANGE_SORT_LOCATION,
  ACTION_CHANGE_SORT_NAME,
}