const ACTION_CHANGE_MAIN_FILTER_TEXT = 'ACTION_CHANGE_MAIN_FILTER_TEXT';
const ACTION_CHANGE_ROWS_DATA = 'ACTION_CHANGE_ROWS_DATA';
const ACTION_CHANGE_NAME_FILTER_TEXT = 'ACTION_CHANGE_NAME_FILTER_TEXT';
const ACTION_CHANGE_INPUT_VISIBILITY = 'ACTION_CHANGE_INPUT_VISIBILITY';

export {
  ACTION_CHANGE_MAIN_FILTER_TEXT,
  ACTION_CHANGE_NAME_FILTER_TEXT,
  ACTION_CHANGE_ROWS_DATA,
  ACTION_CHANGE_INPUT_VISIBILITY
}