const ACTION_CHANGE_MAIN_FILTER_TEXT = 'ACTION_CHANGE_MAIN_FILTER_TEXT';
const ACTION_CHANGE_ROWS_DATA = 'ACTION_CHANGE_ROWS_DATA';

export {
  ACTION_CHANGE_MAIN_FILTER_TEXT,
  ACTION_CHANGE_ROWS_DATA
}